version: "3"

services:
    server:
        container_name: server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8081:8081