version: "3"

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "127.0.0.1:4000:4000"
        volumes:
            - /home/pluge/go-projects/fabric-samples:/app/fabric-samples
        networks: 
            - fabric_test

networks:
    fabric_test:
        external: true
        name: fabric_test
