port: "8081"

server:
  ReadTimeout: 30
  WriteTimeout: 30

db:
  user: "postgres"
  host: "localhost"
  port: "5432"
  password: "1q2w3e4r5t"
  dbname: "postgres"
  sslmode: "disable"

admin:
  email: "admin@admin.admin"
  password: "admin"

ledger:
  mspID: Org1MSP
  certPath: $HOME/go-projects/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem
  keyPath: $HOME/go-projects/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/
  tlsCertPath: $HOME/go-projects/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  peerEndpoint: localhost:7051
  gatewayPeer: peer0.org1.example.com
  channelName: mychannel
  chaincodeName: private